// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asi.proto

package pochemon.proto;

public interface InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cardId = 1;</code>
   */
  int getCardId();

  /**
   * <code>int32 newUserId = 2;</code>
   */
  int getNewUserId();
}
