// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asi.proto

package pochemon.proto;

/**
 * Protobuf type {@code routeguide.Info}
 */
public  final class Info extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:routeguide.Info)
    InfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Info.newBuilder() to construct.
  private Info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Info() {
    cardId_ = 0;
    newUserId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Info(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            cardId_ = input.readInt32();
            break;
          }
          case 16: {

            newUserId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pochemon.proto.RouteGuideProto.internal_static_routeguide_Info_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pochemon.proto.RouteGuideProto.internal_static_routeguide_Info_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pochemon.proto.Info.class, pochemon.proto.Info.Builder.class);
  }

  public static final int CARDID_FIELD_NUMBER = 1;
  private int cardId_;
  /**
   * <code>int32 cardId = 1;</code>
   */
  public int getCardId() {
    return cardId_;
  }

  public static final int NEWUSERID_FIELD_NUMBER = 2;
  private int newUserId_;
  /**
   * <code>int32 newUserId = 2;</code>
   */
  public int getNewUserId() {
    return newUserId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cardId_ != 0) {
      output.writeInt32(1, cardId_);
    }
    if (newUserId_ != 0) {
      output.writeInt32(2, newUserId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cardId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, cardId_);
    }
    if (newUserId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, newUserId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pochemon.proto.Info)) {
      return super.equals(obj);
    }
    pochemon.proto.Info other = (pochemon.proto.Info) obj;

    boolean result = true;
    result = result && (getCardId()
        == other.getCardId());
    result = result && (getNewUserId()
        == other.getNewUserId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARDID_FIELD_NUMBER;
    hash = (53 * hash) + getCardId();
    hash = (37 * hash) + NEWUSERID_FIELD_NUMBER;
    hash = (53 * hash) + getNewUserId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pochemon.proto.Info parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pochemon.proto.Info parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pochemon.proto.Info parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pochemon.proto.Info parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pochemon.proto.Info parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pochemon.proto.Info parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pochemon.proto.Info parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pochemon.proto.Info parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pochemon.proto.Info parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pochemon.proto.Info parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pochemon.proto.Info parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pochemon.proto.Info parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pochemon.proto.Info prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code routeguide.Info}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:routeguide.Info)
      pochemon.proto.InfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pochemon.proto.RouteGuideProto.internal_static_routeguide_Info_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pochemon.proto.RouteGuideProto.internal_static_routeguide_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pochemon.proto.Info.class, pochemon.proto.Info.Builder.class);
    }

    // Construct using pochemon.proto.Info.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cardId_ = 0;

      newUserId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pochemon.proto.RouteGuideProto.internal_static_routeguide_Info_descriptor;
    }

    @java.lang.Override
    public pochemon.proto.Info getDefaultInstanceForType() {
      return pochemon.proto.Info.getDefaultInstance();
    }

    @java.lang.Override
    public pochemon.proto.Info build() {
      pochemon.proto.Info result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pochemon.proto.Info buildPartial() {
      pochemon.proto.Info result = new pochemon.proto.Info(this);
      result.cardId_ = cardId_;
      result.newUserId_ = newUserId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pochemon.proto.Info) {
        return mergeFrom((pochemon.proto.Info)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pochemon.proto.Info other) {
      if (other == pochemon.proto.Info.getDefaultInstance()) return this;
      if (other.getCardId() != 0) {
        setCardId(other.getCardId());
      }
      if (other.getNewUserId() != 0) {
        setNewUserId(other.getNewUserId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pochemon.proto.Info parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pochemon.proto.Info) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int cardId_ ;
    /**
     * <code>int32 cardId = 1;</code>
     */
    public int getCardId() {
      return cardId_;
    }
    /**
     * <code>int32 cardId = 1;</code>
     */
    public Builder setCardId(int value) {
      
      cardId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cardId = 1;</code>
     */
    public Builder clearCardId() {
      
      cardId_ = 0;
      onChanged();
      return this;
    }

    private int newUserId_ ;
    /**
     * <code>int32 newUserId = 2;</code>
     */
    public int getNewUserId() {
      return newUserId_;
    }
    /**
     * <code>int32 newUserId = 2;</code>
     */
    public Builder setNewUserId(int value) {
      
      newUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 newUserId = 2;</code>
     */
    public Builder clearNewUserId() {
      
      newUserId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:routeguide.Info)
  }

  // @@protoc_insertion_point(class_scope:routeguide.Info)
  private static final pochemon.proto.Info DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pochemon.proto.Info();
  }

  public static pochemon.proto.Info getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Info>
      PARSER = new com.google.protobuf.AbstractParser<Info>() {
    @java.lang.Override
    public Info parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Info(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Info> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Info> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pochemon.proto.Info getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

