// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asi.proto

package pochemon.proto;

public final class RouteGuideProto {
  private RouteGuideProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_Info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_Info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_Verification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_Verification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tasi.proto\022\nrouteguide\")\n\004Info\022\016\n\006cardI" +
      "d\030\001 \001(\005\022\021\n\tnewUserId\030\002 \001(\005\"\"\n\014Verificati" +
      "on\022\022\n\nvalidation\030\001 \001(\0102M\n\nRouteGuide\022?\n\017" +
      "ChangeCardOwner\022\020.routeguide.Info\032\030.rout" +
      "eguide.Verification\"\000B)\n\016pochemon.protoB" +
      "\017RouteGuideProtoP\001\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_routeguide_Info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_routeguide_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_Info_descriptor,
        new java.lang.String[] { "CardId", "NewUserId", });
    internal_static_routeguide_Verification_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_routeguide_Verification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_Verification_descriptor,
        new java.lang.String[] { "Validation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
