// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asi.proto

package pochemon.proto;

public interface VerificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Verification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool validation = 1;</code>
   */
  boolean getValidation();
}
